### ISSUE TITLE
There is already an object named 'AspNetRoles' in the database

### ISSUE THREAD

**Issue by PedroNeff** [go2ismail/AdminLTE-Roles-And-Memberships-Example#1]
Hello, i am trying your example and i created a new class and tried to migrate it when the changes to the database are made i get an error "There is already an object named 'AspNetRoles' in the database".
Can you help me to solve this issue?
Thanks in advance!

**Comment by go2ismail** [comment]
hello, i'm not sure the flow process when you add new entity class. but i always minimum follow these three steps: 1. crate new entity model 2. create migration by executing add-migration nameofmigration 3. run the migration by executing update-database
